### ISSUE TITLE
Disabling "Keep running on this site" doesn't work on heise.de

### ISSUE THREAD

**Issue by brezelman** [cavi-au/Consent-O-Matic#159]
Combination of reasons, I think:

- Firefox is returning "Response already sent..." as location.href value for the iframe.
- url is set to "Re" in function contentScriptRunner because of that.
- CMP sourcepointpopup is found in iframe.
- As of debug log, CMP sourcepoint_frame_2022 is detected and corresponding rule is run in triggered UTILITY method.

I'm on Firefox 109.0 (64-bit)

**Comment by PlatoniusIII** [comment]
I think there's more as issue #378 is talking about the same, and today I ran into the same problem on indebuurt.nl
Uncheck "keep running on this site", but if I want to change settings Consent-O-Matic still kicks in and takes over. From the extension's menu there's no option to completely temporarily disable or disable on current tab, so only option is to disable from Firefox add on page.

**Comment by svnhub** [comment]
I believe this is related to a specific missing tabs permission in Firefox preventing CoM from *not* running on pages with iframed popups where the user has selected to disable CoM. In other words it would run always because it could not access the primary URL of the tab to see that it shouldn't. 

This should be fixed in the most recent version. If not please reopen the issue.
