### ISSUE TITLE
Loop on LeMonde.fr

### ISSUE THREAD

**Issue by bristow** [cavi-au/Consent-O-Matic#23]
Hi, Thanks for your incredible add-on !

On https://www.lemonde.fr there is a loop and we can't access on this site...

Thanks !

**Comment by klorydryk** [comment]
I confirm.
And as there is no white list, we need to open another browser to be able to read it :(

**Comment by dkgof** [comment]
You can actually disable Consent-O-Matic for a single site.

Click the extension icon on your menubar, de-select "Keep running on this site?"

This stops the loop for me.

**Comment by klorydryk** [comment]
I tried, but it keeps to loop XD
I guess I should open another issue...

**Comment by dkgof** [comment]
I have committed a fix for the rules, within the next 15min it should be picked up by  your plugin and start working.

The problem was that they send you to another page for the consent, and then back when you press accept.

The rule did not see that the cookie banner was hidden, so even if you already accepted, it sent you to the cookie page, and then back. And then again...

Now it checks if the cookie banner is actually visible before trying to do consent.

**Comment by dkgof** [comment]
It is weird that it keeps looping though, the loop stopped instantly when i deselected the checkbox. Which browser are you using?

**Comment by klorydryk** [comment]
I forced the update and now it's not looping anymore <3
I'm on Firefox 79.0

**Comment by dkgof** [comment]
Great!

**Comment by bristow** [comment]
> I forced the update and now it's not looping anymore <3

How do you make that ? You update add-on or anything else ?

**Comment by klorydryk** [comment]
Lemonde changed his cookie banner
