### ISSUE TITLE
No release since Feb 23rd?

### ISSUE THREAD

**Issue by Kurasami** [cavi-au/Consent-O-Matic#372]
There's updates to this extension repository even yesterday but it hasn't had a proper release in 7 months.

Why is this?

**Comment by AUToelboell** [comment]
Yes there hasn't been a release in 7 months, but all updates so far, since the release, is rules updates or new rules. With a rule update, a new release is not needed. Because the plugin every 22-48 hours checks rules-list.JSON for any updates. Therefore a release is only necessary if an update to the plugin itself has been committed. Yes, a few weeks ago a functionality update was pushed, but hasn't been released yet, due to adding a few debugging and rule editing features. see closed pull request #301.
