### ISSUE TITLE
breitbart.com

### ISSUE THREAD

**Issue by M1Aston** [cavi-au/Consent-O-Matic#438]
https://www.breitbart.com

In cookie settings Social mediahas to be allowed for embedded stuff, like tweets, to work.
As it is now, this is what you get.
![cookie](https://github.com/cavi-au/Consent-O-Matic/assets/43113612/d88a87e8-4ffe-48cc-9901-3ba99e663c07)

Please fix this.

**Comment by svnhub** [comment]
Do you have analytics tracking enabled in your preferences in the extension? Otherwise it is going to disable them by default.

In the cases where sites do not accept your preferences and require more tracking in order to earn money on delivering the content that you would like to consume you may have to manually give them more tracking access.

**Comment by M1Aston** [comment]
Enabling "Ad selection, delivery and reporting" fixed it.

Privacy is important to me, but breaking websites (especially a news site) is not worth the hassle. I hope extensions like ublock and Cookie Autodelete will offer some privacy protection while sites keep working normally.

**Comment by svnhub** [comment]
Yeah, some sites even make it more extreme with the track-or-pay strategy in which case you cannot see any content at all without  either having to allow them to track you or having to pay them. And if you pay them it is unclear if they are just tracking you still anyways.

I'll close this issue since it is more of a political issue with the current state of things on the web rather than a technical one related to the extension.
