### ISSUE TITLE
Notification / change in icon when new version update available

### ISSUE THREAD

**Issue by nicoleahmed** [cavi-au/Consent-O-Matic#450]
Hi
Thanks for maintaining this great extension. I use the latest version of the extension on the latest version of Chrome.

It would be great if there was an icon indicator and extension message when there are new versions of the extension released please.

Other "unpacked extensions" manage this with a change to the icon on the extension toolbar 
A message on the extension dashboard with a link to the new release would be great too

Also when installing - can the extension folder just be dropped over the old extension folder? At the moment my stats get overwritten when I update to new versions. 

Thank you
Nicole

**Comment by svnhub** [comment]
We recommend using the Chrome Web Store for installing this extension. That will also automatically update the extension whenever a new release is made:
https://chromewebstore.google.com/detail/mdjildafknihdffpkfmmpnpoiajfjnjd

Future versions of this git repository will be more complicated to load in "unpacked" mode due to how Manifest V3 requires us to rebuild the extension and pack it for distribution across all the major browsers. It will not be impossible to keep doing that as a user, as the entire build process will remain open, but certainly not recommended for daily use. To avoid having too many development trees we will focus on the official distribution channels unless they do something incredibly stupid (please no more manifest version updates this year, looking at you, Chrome...).

Furthermore I think maybe Chrome treats unpacked extensions as new unless you "update" them instead of "load unpacked" again through the UI. In that case they do not have access to old data. For this you can just drop the new release on top of the old one.
Keep in mind that for the manifest v3 update currently in the master repository things are changing a lot.
