### ISSUE TITLE
High cpu usage for youtube

### ISSUE THREAD

**Issue by Szpadel** [cavi-au/Consent-O-Matic#49]
I found issue on youtube (but issue is probably not limited to only that site)
Where extension is constantly executing via MutationCalback and is doing a lot of `Document.querySelectorAll` calls causing 100% cpu usage.

![image](https://user-images.githubusercontent.com/1857251/160241015-53652cab-8a76-4c47-9de8-aa8266458998.png)
here you can see profile record for youtube site (with paused video) and as you can see this extension is responsible for 96% of cpu time

Issue reproduced on chrome and firefox.
I think there should be some debouncing introduced here and maybe some timeout when extension no longer tries to look for popup (eg. if nothing was detected for eg. 30s then we unsubscribe from all events) and allso after popup was handled (not sure if that is implemented already)

**Comment by svnhub** [comment]
I think this bug may have been already fixed in the code in the repository but not yet pushed to the store. Did you use the add-on via one of the add-on stores?

Feel free to try the code from the master branch here from git (both Firefox and Chrome supports unpacked extensions either via about:debugging -> This Firefox -> Load Temporary Addon -> Extension/manifest.json (firefox) or Manage Extensions -> Load Unpacked (Chrome)

**Comment by svnhub** [comment]
Now you can also try out the new version 1.0.0 releasing very soon in the stores - please re-open the issue if this did not fix it

**Comment by Szpadel** [comment]
FYI I tested it since yesterday directly from master, and I didn't reproduced this issue so far

**Comment by svnhub** [comment]
Good to know, thanks!
