### ISSUE TITLE
Consent-o-matic is visually blocking

### ISSUE THREAD

**Issue by grandeljay** [cavi-au/Consent-O-Matic#54]
Sometimes when sites load slow or have really elaborate consent forms and it takes up to about 10 or even 30 seconds where I have to impatiently wait for the magic to happen. 

I think it would be better if consent-o-matic didn't have a modal but would just be a little box somewhere and still allows me to interact with the page.

I often just want to scroll or start searching the text for a specific term but I can't because the consent form is still being processed.

**Comment by dkgof** [comment]
The biggest problem with this, is that some of the consent forms, listens for clicks outside the consent form, and interpret this as consent given. Which means that if we are not done filling the form, then it might not be the correct consent that ends up being given.

**Comment by grandeljay** [comment]
Would you consider an extra option which would disable the modal anyway? Or that hitting ESC would abort the process? You can still point out that the consenting process would likely be "cancelled" if you interact with the site before consent-o-matic is finished.

I believe that the user should always remain in control, even for reckless actions and I think this would be a really big improvement for the user.

**Comment by dkgof** [comment]
That might very well be an option, we will discuss it.

**Comment by svnhub** [comment]
We are looking into changing the visual look-and-feel during auto-filling of the forms considerably in the next version with a bit of an experimental rewrite of the progress dialog UI: Rules may capture the consent popups  (that are typically fullscreen and blocking interaction) and move them out of the way while they are being filled out automatically so that the user can continue working with the page itself.

Many of the rules will probably need to be revisited to make sure that this new way of interacting with the CMP does not break anything.

![image](https://user-images.githubusercontent.com/13135124/174828165-7044bbb1-0ea8-40e1-baa7-1f39b8be3e60.png)

**Comment by grandeljay** [comment]
Sweet, thanks for letting me know. I will put my PR (#62) on hold then.

**Comment by svnhub** [comment]
This feature was included in v1.0.8 that is being released now

**Comment by grandeljay** [comment]
Thank you, I love it!
