### ISSUE TITLE
Deal with consent forms that are on a secondary page

### ISSUE THREAD

**Issue by edas** [cavi-au/Consent-O-Matic#6]
Hi

Some sites redirect to a secondary webpage to give or refuse consents. Is there a way to tell the extension to open a page in an hidden way and continue the consent process with this hidden page?

Exemple with https://www.francetvinfo.fr/

At first access you have a popin at the lower right corner. You access to the consent panel by  clicking on "paramétrez vos cookies et consentements" ("tune your cookies and consents") but the opening panel isn't complete. Some consent switches are behind the "politique de gestion des cookies et sdk" ("cookies and sdk policies") link which redirect to a secondary page on the domain of the mother company. 

There you have to scroll down to the end of the page and click on the button "gérer les cookies" ("tune cookies") to have access to other options (these are different, someare only on the first page, some are only on this secondary page).

This is important because most of these secondary switches are « on » by default, even is they shouldn't legaly. 

If I make the extension click on the "politique de gestion des cookies et sdk" ("cookies and sdk policies") link I'm redirected and I have no way to go back with the extension (and even if I could, this would be an horrible experience)

**Comment by dkgof** [comment]
I can see the problem, being that it opens the page in the same tab, so it overrides the page. It could be possible to make a open url in new tab action, but there might not always be a visible url from the dom, it could be a javascript event handler that listens for a click and redirects.

I think until now, when a widget has the option to send you along to completely different page, for even more cookie options, the plugin has not handled it.

Mainly because it would interrupt the browsing experience of the user, and thus be annoying.

I will take a look at an open in another tab action, but as i wrote, it would have to be able to get its url from somewhere in the dom.

**Comment by dkgof** [comment]
I just updated the rules engine with another option for ClickAction.

ctrlKey: true/false, defaults to false.

When set to true, the addon simulates a ctrl+click which tells the browser to open in a new tab, instead of in the current tab. Hopefully this is usefull for the pesky CMP you were trying to add support for :)

**Comment by edas** [comment]
Awesome! Thank you
