### ISSUE TITLE
Inacessible UI elements on the options/settings to choose which things to refuse

### ISSUE THREAD

**Issue by bingen13** [cavi-au/Consent-O-Matic#69]
The interface to choose which categories to grant or deny consent for is inaccessible. Screen readers do not correctly detect whether the setting is to grant or to deny.

A simple solution would be using standard checkbox elements. Some other mechanism such as including a text on the clickable element might work as well.

**Comment by dkgof** [comment]
Hi,

I tried to make some changes that hopefully helps, but since im not familiar with screen readers at all, would you be able to help test it?

If you can clone the current repository, and then load the extension as an unpacked extension in for example chrome or edge?

And then test if its any better?

**Comment by bingen13** [comment]
Hi,

I just tested the unpacked extension with FF 101.0.1 and it works fine. Thanks!

**Comment by dkgof** [comment]
Great, thanks! We will include the changes in the next release.

**Comment by svnhub** [comment]
This feature is included in v1.0.8 which is being released
