### ISSUE TITLE
App prevent interaction and continue processing info

### ISSUE THREAD

**Issue by Asbjoedt** [cavi-au/Consent-O-Matic#87]
Thank you for your extension, helping to get rid of cookie pop-ups.

I am having trouble accessing this websit having conseto-matic turned on. The program will show a small window in the right lower corner, which keeps scrolling through some cookie information. and it will prevent from any interaction/use of the website i.e. window cannot be scrolled down.

The website with the problem: https://www.infoworld.com/article/3574510/how-to-use-named-and-optional-parameters-in-csharp.html

**Comment by svnhub** [comment]
Can confirm that there are two issues with the popup at infoworld:
1) They lock scrolling of the main content while their consent popup is open
2) It requires an extraordinary amount of scrolling and clicks. This influences the amount of time that it takes to fill out the popup in the preview mode (where every click is shown visually) beyond what was intended. This is clearly something that has to be addressed

For a temporary solution while we discuss how to solve this properly please have a look at https://github.com/cavi-au/Consent-O-Matic/issues/81#issuecomment-1172853185 on how to disable the picture-in-picture mode and switch to the hidden mode where processing happens in the background instead.

Long term the intention is to have a working picture-in-picture mode for educational purposes, and to allow people to verify that popups are filled properly after just having installed the add-on; while also allowing (and recommending) an easy switch to the hidden background processing mode, which is usually faster. This switch is not yet available in the UI except from the secret ninja settings.

**Comment by Asbjoedt** [comment]
Hi
Thx for reply.
I cannot find debug button in options as guided in #81 .
Secondly, the picture-in-picture mode should not just be recommended, it should be default. There's other ways of informing user the extension is working, than showing the window processing.

**Comment by choco-latin** [comment]
Hi, I just ran in the same problem with the website of [The Times](https://www.thetimes.co.uk/) (very long animation without the possibility to interact with the website).

As a user I would prefer not having to see this, even though I understand the educational purpose. Could it be an option?

**Comment by svnhub** [comment]
Just a quick update on some of the facets of this issue:

Scroll-blocking
Sites that prevent interaction with the site while the cookie popup is shown fall into two categories: Sites with embedded popups and sites with iframe-based popups. We just added code for a new scroll-hijacking prevention mechanism for sites with embedded popups and it seems to be performing well in tests so far, allowing interaction with the site while the popup is filled. Unfortunately both examples in this thread are iframe-based so this doesn't help much here.

Long animation times in Picture-in-Picture educational mode: The overall click delay will be shortened in general and if many clicks are required the delay removed entirely. Unfortunately the specific issue seen on The Times and Infoworld relate to the sourcepoint-frame-2022 rule which is taking very long to process on some systems because of the extreme number of affiliate partners on those sites. It appears that even in hide-mode where all clicks are dispatched as quickly as possible these sites take considerable time to process.

More effort will have to go into finding the exact reason why this is taking so long on some systems.

**Comment by svnhub** [comment]
Two separate fixes for the original issue are included in v.1.0.9 which is being released now:
- First of all the scroll-hijack prevention should allow you to interact with the page and scroll while the popup is handled
- Secondly the handling of the popup has been sped up greatly
